"""Build a deterministic, source-linked GitHub wiki; no model or provider calls."""
from __future__ import annotations
import argparse
import ast
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile
from urllib.parse import quote, unquote, urlsplit

ROOT = Path(__file__).resolve().parents[2]
SCHEMA = 'asset-director.live-wiki/1'
MANIFEST = '.live-wiki-manifest.json'
MARKER = '<!-- Generated by tools/wiki/build.py; edit the linked repository source. -->'
PAGE = re.compile(r'[A-Za-z0-9][A-Za-z0-9-]*|_Sidebar|_Footer')
SHA = re.compile(r'[a-f0-9]{40}')
LINK = re.compile(r'(\]\()(<[^>]+>|[^\s()]+)(\s+"[^"]*")?(\))')


def digest(data):
    return hashlib.sha256(data).hexdigest()


def text(path):
    return path.read_text(encoding='utf-8-sig')


def git(root, *args):
    return subprocess.check_output(['git', '-C', str(root), *args], text=True).strip()


def checked(root, relative):
    path = root / relative
    if not path.resolve().is_relative_to(root.resolve()):
        raise ValueError('Source path escapes repository: ' + relative)
    if path.is_symlink() or any(p.is_symlink() for p in path.parents if p != root.parent):
        raise ValueError('Symlink source refused: ' + relative)
    if not path.is_file():
        raise ValueError('Missing source: ' + relative)
    return path


def render_links(body, source, pages, root, base, commit):
    """Rewrite prose links, leaving fenced examples untouched."""
    def target(value):
        raw = value.strip('<>')
        url = urlsplit(raw)
        if url.scheme or raw.startswith(('#', '//')):
            return value
        relative = (Path(source).parent / unquote(url.path)).as_posix()
        normalized = os.path.normpath(relative).replace('\\', '/')
        path = root / normalized
        if not path.resolve().is_relative_to(root.resolve()):
            raise ValueError('Relative link escapes repository: ' + raw)
        if normalized in pages:
            result = pages[normalized]
        elif path.exists():
            kind = 'tree' if path.is_dir() else 'blob'
            result = base + '/' + kind + '/' + commit + '/' + quote(normalized, safe='/')
        else:
            raise ValueError('Broken source link in ' + source + ': ' + raw)
        return result + ('?' + url.query if url.query else '') + ('#' + url.fragment if url.fragment else '')
    result, fence = [], None
    for line in body.splitlines(keepends=True):
        match = re.match(r'^\s{0,3}(`{3,}|~{3,})', line)
        if match:
            delim = match[1]
            if fence is None:
                fence = delim
            elif delim[0] == fence[0] and len(delim) >= len(fence):
                fence = None
            result.append(line)
        elif fence:
            result.append(line)
        else:
            line = LINK.sub(lambda m: m[1] + target(m[2]) + (m[3] or '') + m[4], line)
            ref = re.match(r'^(\s{0,3}\[[^]]+\]:\s*)(\S+)(.*)$', line)
            if ref:
                line = ref[1] + target(ref[2]) + ref[3] + ('\n' if line.endswith('\n') else '')
            result.append(line)
    return ''.join(result)


def source_index(root, base, commit):
    rows = ['# Source index', '', 'Automatically lists tracked public documentation and source modules. '
            'Dated acceptance/handoff documents describe their recorded revision, not current test results.', '',
            '| Source | Module description or document title |', '|---|---|']
    paths = git(root, 'ls-files').splitlines()
    for name in paths:
        if name.startswith(('docs/', 'wiki/', 'skills/')) and name.endswith('.md'):
            value = text(checked(root, name))
            heading = next((line.lstrip('# ').strip() for line in value.splitlines() if line.startswith('# ')), '')
        elif name.startswith(('src/asset_director/', 'launcher/lib/')) and name.endswith(('.py', '.mjs')):
            value = text(checked(root, name))
            heading = (ast.get_docstring(ast.parse(value)) or '').split('\n')[0] if name.endswith('.py') else 'Launcher module; consult source.'
        else:
            continue
        heading = heading.replace('|', '\\|').replace('\n', ' ')
        rows.append(f'| [{name}]({base}/blob/{commit}/{quote(name, safe="/")}) | {heading} |')
    return '\n'.join(rows) + '\n'


def build(root, output, repository, commit, branch):
    if Path(output).is_symlink():
        raise ValueError('Symlink output refused')
    root, output = Path(root).resolve(), Path(output).resolve()
    if not SHA.fullmatch(commit) or not re.fullmatch(r'[\w.-]+/[\w.-]+', repository):
        raise ValueError('Expected a full commit SHA and owner/repository')
    if not branch or any(c in branch for c in '\n\r`'):
        raise ValueError('Invalid source branch')
    if output.exists() and any(output.iterdir()):
        raise ValueError('Build into a fresh empty directory, never a checkout or an existing wiki')
    config = json.loads(text(checked(root, 'wiki/config.json')))
    if config.get('schema') != 'asset-director.live-wiki-config/1':
        raise ValueError('Unknown wiki configuration schema')
    mapping = config['pages']
    reserved = {'CLI-Reference', 'Job-Operations', 'Evidence-Inventory', 'Workflow-Reference',
                'Source-Index', 'Build-Identity', '_Sidebar', '_Footer'}
    if 'Home' not in mapping or reserved & mapping.keys():
        raise ValueError('Missing Home or reserved generated page name')
    if len({name.casefold() for name in mapping}) != len(mapping):
        raise ValueError('Case-insensitive page name collision')
    tracked = set(git(root, 'ls-files').splitlines())
    if any(path not in tracked or not path.endswith('.md') for path in mapping.values()):
        raise ValueError('Wiki sources must be tracked Markdown files')
    if len(mapping) != len(set(mapping.values())):
        raise ValueError('Each source may be mirrored once only')
    if any(not PAGE.fullmatch(name) for name in mapping):
        raise ValueError('Unsafe wiki page name')
    base = 'https://github.com/' + repository
    by_source = {path: name for name, path in mapping.items()}
    bodies = {name: render_links(text(checked(root, path)), path, by_source, root, base, commit)
              for name, path in mapping.items()}
    # Inspect the actual portable parser/contracts, isolated from user settings.
    with tempfile.TemporaryDirectory(prefix='wiki-catalog-') as tmp:
        env = {'PATH': os.environ.get('PATH', ''), 'SYSTEMROOT': os.environ.get('SYSTEMROOT', ''),
               'HOME': tmp, 'USERPROFILE': tmp, 'BAD_CONFIG': str(Path(tmp)/'absent-runtime.json'),
               'CODEX_HOME': tmp, 'COLUMNS': '88', 'PYTHONIOENCODING': 'utf-8'}
        raw = subprocess.check_output([sys.executable, '-I', str(root/'tools/wiki/catalog.py')],
                                      cwd=root, env=env, text=True, encoding='utf-8', timeout=60)
        catalog = json.loads(raw)
    bodies['CLI-Reference'] = '# CLI reference\n\nGenerated from the actual argument parser, without executing commands. '
    bodies['CLI-Reference'] += 'Use the installed `scripts/director.py` entry point with your own library.\n\n'
    for name, help_text in catalog['commands'].items():
        bodies['CLI-Reference'] += '## ' + name + '\n\n```text\n' + help_text + '```\n\n'
    bodies['Job-Operations'] = '# Job operation reference\n\nGenerated from `asset_director.jobs.OPS`. '
    bodies['Job-Operations'] += 'An allowed field is not necessarily required or supported for every input. '
    bodies['Job-Operations'] += 'Read [job contracts](Job-Execution) for validation, approval and preservation rules.\n\n'
    bodies['Job-Operations'] += '| Operation | Allowed top-level option fields |\n|---|---|\n'
    for name, fields in catalog['operations'].items():
        bodies['Job-Operations'] += '| `' + name + '` | ' + ', '.join('`'+f+'`' for f in fields) + ' |\n'
    bodies['Evidence-Inventory'] = '# Evidence inventory\n\nGenerated from `tools/ci/contracts.py`; this is required coverage, '
    bodies['Evidence-Inventory'] += '**not a claim that these checks passed**.\n\n'
    bodies['Evidence-Inventory'] += '| Required partition | Ordered checkpoints |\n|---|---|\n'
    for partition, checks in catalog['partitions']:
        bodies['Evidence-Inventory'] += '| ' + ' / '.join(partition) + ' | ' + ' → '.join(checks) + ' |\n'
    workflows = sorted((root/'.github/workflows').glob('*.yml')) + sorted((root/'.github/workflows').glob('*.yaml'))
    bodies['Workflow-Reference'] = '# Workflow reference\n\nGenerated from every checked-in workflow. '
    bodies['Workflow-Reference'] += 'The complete YAML below is authoritative; see [CI and E2E](CI-and-E2E) for the journey map.\n\n'
    for path in sorted(workflows):
        relative = path.relative_to(root).as_posix()
        value = text(checked(root, relative))
        bodies['Workflow-Reference'] += f'## {path.name}\n\n[Exact source]({base}/blob/{commit}/{relative})\n\n```yaml\n{value}\n```\n\n'
    bodies['Source-Index'] = source_index(root, base, commit)
    bodies['Build-Identity'] = ('# Build identity\n\n'
        f'| Property | Value |\n|---|---|\n| Source branch | `{branch}` |\n'
        f'| Source commit | [{commit}]({base}/commit/{commit}) |\n'
        f'| Runtime declaration | `{catalog["version"]}` |\n'
        f'| CLI commands | {len(catalog["commands"])} |\n| Job operations | {len(catalog["operations"])} |\n'
        f'| Workflows | {len(workflows)} |\n| Required evidence partitions | {len(catalog["partitions"])} |\n\n'
        f'[Current Actions]({base}/actions?query=branch%3A{quote(branch, safe="")})\n\n'
        'Publishing documentation does not establish acceptance or release a build. '
        'Check an Actions run with the same full source commit. No model/provider calls are made to build this wiki.\n')
    bodies['_Sidebar'] = '# Asset Director\n\n' + '\n'.join(f'- [{name.replace("-", " ")}]({name})' for name in bodies) + '\n'
    bodies['_Footer'] = f'[Home](Home) · [Build identity](Build-Identity) · [Update policy](Live-Wiki) · [Source]({base})\n'
    output.mkdir(parents=True, exist_ok=True)
    pages = {}
    for name, body in bodies.items():
        source = mapping.get(name, 'tools/wiki/build.py')
        header = (MARKER + '\n\n' + f'> Source: `{branch}` · [{commit[:12]}]({base}/commit/{commit}). '
                  f'[Edit source]({base}/blob/{commit}/{source}). Generated documentation, not a test result.\n\n')
        data = (header + body.rstrip() + '\n').encode('utf-8')
        (output/(name+'.md')).write_bytes(data)
        pages[name+'.md'] = digest(data)
    # Validate all generated relative wiki links after every page name is known.
    for path in output.glob('*.md'):
        fence = False
        for line in text(path).splitlines():
            if re.match(r'^\s{0,3}(`{3,}|~{3,})', line):
                fence = not fence
            if not fence:
                for match in LINK.finditer(line):
                    target = urlsplit(match[2].strip('<>'))
                    if not target.scheme and target.path and target.path+'.md' not in pages:
                        raise ValueError('Broken wiki link in '+path.name+': '+match[2])
    manifest = {'schema': SCHEMA, 'repository': repository, 'source_commit': commit,
                'source_branch': branch, 'pages': pages}
    (output/MANIFEST).write_text(json.dumps(manifest, indent=2, sort_keys=True)+'\n', encoding='utf-8')
    return manifest


if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--output', required=True)
    p.add_argument('--repository', required=True)
    p.add_argument('--commit', required=True)
    p.add_argument('--branch', required=True)
    args = p.parse_args()
    result = build(ROOT, args.output, args.repository, args.commit, args.branch)
    print(json.dumps({'status': 'BUILT', 'source_commit': result['source_commit'], 'pages': len(result['pages'])}))
