/** Generated-only user journey: editable native clips and explicit body turns. */
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {randomUUID} from 'node:crypto';
import {createApp} from '../launcher/server.mjs';
import {exists,fileHash,json,writeJson} from '../launcher/lib/storage.mjs';
const [out,generated,python,blender,playwright,chrome]=process.argv.slice(2);
assert([out,generated,python,blender,playwright].every(v=>v&&path.isAbsolute(v)));
assert(!await exists(out));const fixture=await json(path.join(generated,'RESULTS.json'));
assert.equal(fixture.status,'PASS');assert.equal(fixture.input_kind,'GENERATED');await fs.mkdir(out,{recursive:true});
const repo=fileURLToPath(new URL('../',import.meta.url)),source=path.join(generated,'source.blend'),original=await fileHash(source);
const report={kind:'generated-motion-edits-browser',checks:[],errors:[],requests:[],not_tested:['Live runtime or user projects','Human contact or creative acceptance','Automatic choreography or foot IK']};
let app,browser,page;
try{
 app=await createApp({root:path.join(out,'Studio'),port:0,config:{python,blender,skill:path.join(repo,'skills/blender-asset-director'),library:path.join(out,'Studio/Database/AssetDirector')}});
 const auditJob=await app.runtime.harness(['job-prepare','scene-audit','--input',source]),audit=await app.workbench.result(await app.runtime.harness(['job-run',auditJob.id,'--blender',blender]));
 let project=await app.store.create('Synthetic editable transitions','Generated geometry and native joint animation only');await app.workbench.create(project.id,project.revision,'Clip editing');project=await app.store.get(project.id);
 const scene=project.workbench.scenes[0],cpId='cp_'+randomUUID(),relative='Scenes/'+cpId+'.blend';await fs.copyFile(source,path.join(project.directory,relative),fs.constants.COPYFILE_EXCL);
 scene.checkpoints.push({id:cpId,path:relative,...original,parent:null,stage:'world',audit});scene.current=cpId;scene.stage='action';scene.completed={world:cpId};await app.store.save(project,project.revision);
 const {chromium}=await import(pathToFileURL(playwright).href);browser=await chromium.launch(chrome?{executablePath:chrome}:{channel:'chrome'});page=await browser.newPage({viewport:{width:1440,height:1000},serviceWorkers:'block'});page.setDefaultTimeout(30000);
 const redact=v=>String(v).replaceAll(app.token,'[REDACTED]');page.on('pageerror',e=>report.errors.push(redact(e.message)));page.on('console',m=>{if(m.type()==='error')report.errors.push(redact(m.text()));});page.on('dialog',d=>d.dismiss());
 page.on('request',r=>{if(r.url().startsWith(app.origin+'/'))report.requests.push({path:new URL(r.url()).pathname,method:r.method()});else if(/^https?:/.test(r.url()))report.errors.push('Unexpected external request');});
 const ready=()=>page.waitForFunction(()=>!document.body.classList.contains('working')&&document.querySelector('[data-scene-viewer]')?.dataset.viewerState==='ready'&&!document.querySelector('[data-action-field="performer"]')?.disabled,null,{timeout:205000});
 const click=async selector=>{await page.locator('body').ariaSnapshot();await page.locator(selector).click();await page.waitForFunction(()=>!document.body.classList.contains('working'));};
 const field=name=>page.locator(`[data-motion-field="${name}"]`),save=()=>page.locator('[data-action="action-save"]'),clips=()=>page.locator('.motion-clip'),joins=()=>page.locator('.motion-transition');
 const advanced=async()=>{const details=page.locator('[data-motion-details]');if(!await details.evaluate(e=>e.open))await click('[data-motion-details] > summary');};
 const takeLabel='Observed 0 1';
 const selectClip=async index=>{await clips().nth(index).click();await page.locator('body').ariaSnapshot();};
 const saveAndRead=async()=>{assert(await save().isEnabled(),'Save is enabled for the valid local edit');const before=(await app.store.get(project.id)).workbench.scenes[0].current,prior=new Set((await app.store.runs(project.id)).map(r=>r.id));await click('[data-action="action-save"]');await ready();project=await app.store.get(project.id);const s=project.workbench.scenes[0],cp=s.checkpoints.find(c=>c.id===s.current),runs=await app.store.runs(project.id);const edit=runs.find(r=>r.action==='action-edit'&&!prior.has(r.id));assert.equal(edit?.state,'SUCCEEDED',edit?.error||'Native edit did not succeed');assert.notEqual(cp.id,before,'Every Save creates a separate checkpoint');const run=runs.find(r=>r.action==='action-audit'&&r.checkpointId===cp.id&&r.state==='SUCCEEDED');assert(run,'Native saved inspection published');assert.deepEqual(s.completed,{world:cpId});return {cp,rig:run.inspection.performers.find(p=>p.name==='TestPerformer0')};};
 await page.goto(app.origin+'/workbench#'+app.token);await click(`[data-action="project"][data-id="${project.id}"]`);await ready();await click('[data-action="motion-enable"]');await page.getByLabel('Performer',{exact:true}).selectOption('TestPerformer0');
 await page.getByLabel('Add animation').selectOption({label:'Observed 0 0'});await field('travel').check();await field('pace').fill('1');await field('direction').fill('-90');
 await page.getByLabel('Add animation').selectOption({label:takeLabel});await field('travel').check();await field('pace').fill('1');await field('direction').fill('0');
 await joins().first().click();assert(await page.getByText('Selected transition',{exact:true}).isVisible());await field('transition_mode').selectOption('turn');await field('transition_frames').fill('12');await field('heading_deg').fill('90');
 assert.equal(await joins().count(),1);assert.equal(await clips().count(),2);assert(await save().isEnabled());assert.equal(report.requests.filter(r=>r.path.endsWith('/action-save')).length,0);
 await page.screenshot({path:path.join(out,'01-turn-inspector.png'),fullPage:true});report.checks.push('Transition independently selectable; mode, added duration and body turn change only the local draft');
 const first=await saveAndRead();assert.equal(first.rig.timeline.clips[1].heading_deg,90);assert.equal(first.rig.timeline.connections[0].mode,'turn');assert.equal(first.rig.timeline.connections[0].contact_acceptance,'NOT_EVALUATED');
 const firstHash=await fileHash(path.join(project.directory,first.cp.path));
 await page.reload();await ready();await selectClip(1);assert.equal(await field('pace').inputValue(),'1');await field('distance').fill('1.5');
 assert(await save().isDisabled(),'Repeating generated motion requires an explicit review');await field('repeat_reviewed').check();
 const revised=await saveAndRead();assert.notEqual(revised.cp.id,first.cp.id);assert.deepEqual(revised.rig.timeline.clips[0],first.rig.timeline.clips[0]);assert.equal(revised.rig.timeline.clips[1].travel.meters_per_cycle,1);assert.equal(revised.rig.timeline.clips[1].frames,37);
 assert.deepEqual(await fileHash(path.join(project.directory,first.cp.path)),firstHash);report.checks.push('Real Blender Save/reload permits later distance revision without retyping pace; earlier native clip and previous checkpoint remain intact');
 await selectClip(1);await page.getByLabel('Replace animation').selectOption({label:'Observed 0 0'});assert(!await field('travel').isChecked());assert.equal(await page.getByLabel('Replace animation').inputValue(),first.rig.timeline.clips[0].take_id);await click('[data-action="action-undo"]');assert.equal(await field('distance').inputValue(),'1.5');
 await click('[data-action="motion-select-transition"]');await click('.motion-insert > summary');await page.getByLabel('Insert animation before this clip').selectOption({label:'Observed 0 0'});assert.equal(await clips().count(),3);await click('[data-action="action-undo"]');assert.equal(await clips().count(),2);
 await click('[data-action="motion-delete"]');assert.equal(await joins().count(),0);await click('[data-action="action-undo"]');assert.equal(await joins().count(),1);
 report.checks.push('Replacement, observed intermediate insertion and connection removal are distinct local operations and Undo restores each');
 await click('[data-action="motion-select-clip"]');await field('travel').uncheck();if(await field('repeat_reviewed').isChecked())await field('repeat_reviewed').uncheck();await click('[data-motion-trim] > summary');await field('source_in').fill('3');await field('source_out').fill('21');
 const trimmed=await saveAndRead();assert.deepEqual(trimmed.rig.timeline.clips[1].source_range,[3,21]);assert.equal(trimmed.rig.timeline.clips[1].frames,19);
 await selectClip(1);const splitFrame=trimmed.rig.timeline.clips[1].start+9;
 await page.locator('[data-view="time"]').evaluate((input,value)=>{input.value=String(value);input.dispatchEvent(new Event('input',{bubbles:true}));},(splitFrame-1)/24);
 await click('[data-action="motion-split"]');assert.equal(await clips().count(),3);const split=await saveAndRead();assert.equal(split.rig.timeline.clips.length,3);assert.deepEqual(split.rig.timeline.clips[1].source_range,[3,11]);assert.deepEqual(split.rig.timeline.clips[2].source_range,[12,21]);
 report.checks.push('Trim and split use observed native source frames, execute in Blender and retain exact separate clip identities on reload');
 await page.reload();await ready();await selectClip(2);await page.locator('[data-view="play"]').click();await page.waitForFunction(()=>Number(document.querySelector('[data-view="time"]').value)>2);await page.locator('[data-view="play"]').click();await page.screenshot({path:path.join(out,'02-saved-editable-playback.png'),fullPage:true});
 await selectClip(0);await page.getByRole('button',{name:'Move path endpoint',exact:true}).waitFor({state:'visible'});await page.screenshot({path:path.join(out,'03-red-path-desktop.png'),fullPage:true});
 const postsBeforeFraming=report.requests.filter(r=>r.method==='POST').length;
 await field('distance').fill('20');await click('[data-view="reset"]');await page.getByRole('button',{name:'Move path endpoint',exact:true}).waitFor({state:'visible'});
 const canvas=await page.locator('.viewer-canvas').boundingBox(),handle=await page.getByRole('button',{name:'Move path endpoint',exact:true}).boundingBox();assert(handle.x>canvas.x&&handle.x+handle.width<canvas.x+canvas.width,'Reset frames a long path without clipping its handle');
 await click('[data-action="action-undo"]');await click('[data-view="reset"]');assert.equal(report.requests.filter(r=>r.method==='POST').length,postsBeforeFraming,'Camera framing and Undo do not save a draft');report.checks.push('Long offscreen draft paths can be framed with Reset view without saving or moving the character');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'04-mobile-editor.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(await fileHash(source),original);assert.deepEqual(await fileHash(path.join(project.directory,relative)),original);assert.deepEqual(report.errors,[]);
 report.checks.push('Saved combined scene plays; red path remains visible; mobile has no page overflow; source bytes and original checkpoint preserved');
 report.status='PASS';report.projectId=project.id;report.checkpoints=[first.cp,revised.cp,trimmed.cp,split.cp].map(({id,sha256})=>({id,sha256}));
}catch(error){report.status='FAIL';report.error=String(error).replaceAll(app?.token||'never-match-token','[REDACTED]');process.exitCode=1;if(page)await page.screenshot({path:path.join(out,'FAILURE.png'),fullPage:true}).catch(()=>{});}
finally{await browser?.close();if(app){app.server.closeAllConnections();await new Promise(resolve=>app.server.close(resolve));}await writeJson(path.join(out,'RESULTS.json'),report);console.log(JSON.stringify({status:report.status,checks:report.checks.length,error:report.error}));}
