/** Explicit older-scene preparation through the real browser and native worker. Synthetic only. */
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createApp} from '../launcher/server.mjs';
import {exists,fileHash,json,writeJson} from '../launcher/lib/storage.mjs';
const [out,generated,python,blender,playwright,chrome]=process.argv.slice(2);
assert([out,generated,python,blender,playwright].every(x=>x&&path.isAbsolute(x))&&!await exists(out));
assert.equal((await json(path.join(generated,'world_layers_report.json'))).status,'PASS');
const source=path.join(generated,'baseline-failure.blend'),before=await fileHash(source),repo=fileURLToPath(new URL('../',import.meta.url));
await fs.mkdir(out,{recursive:true});
const report={kind:'synthetic-world-preparation-browser',checks:[],errors:[],requests:[],saved:[],human_review:'NOT_TESTED',native_desktop:'NOT_TESTED',scripted_decisions:['Generated asset groups and Save only; no human creative acceptance']};
let app,browser,page;
try{
 app=await createApp({root:path.join(out,'Studio'),port:0,config:{python,blender,skill:path.join(repo,'skills/blender-asset-director'),library:path.join(out,'Studio/Database/AssetDirector')}});
 const headers={Authorization:'Bearer '+app.token,'Content-Type':'application/json'};
 let p=await app.store.create('Synthetic older World preparation','Generated keyed rigs, independent prop and reversible placement preparation');await app.workbench.create(p.id,p.revision,'Existing imports');p=await app.store.get(p.id);
 const scene=p.workbench.scenes[0],cpId='cp_'+randomUUID(),relative='Scenes/'+cpId+'.blend';await fs.copyFile(source,path.join(p.directory,relative),fs.constants.COPYFILE_EXCL);
 const prepared=await app.runtime.harness(['job-prepare','scene-audit','--input',source]),audit=await app.workbench.result(await app.runtime.harness(['job-run',prepared.id,'--blender',blender]));
 scene.checkpoints.push({id:cpId,path:relative,...before,parent:null,stage:'world',audit});scene.current=cpId;scene.completed={world:cpId};p=await app.store.save(p,p.revision);
 const manifestBefore=await fileHash(path.join(p.directory,'project.json'));
 const state=async()=>{const r=await fetch(app.origin+'/api/workbench/state?'+new URLSearchParams({projectId:p.id,compact:true}),{headers});assert.equal(r.status,200);return r.json();};
 const {chromium}=await import(pathToFileURL(playwright).href);browser=await chromium.launch(chrome?{executablePath:chrome}:{channel:'chrome'});page=await browser.newPage({viewport:{width:1440,height:1000},serviceWorkers:'block'});page.setDefaultTimeout(30000);
 page.on('pageerror',e=>report.errors.push(e.message.replaceAll(app.token,'[REDACTED]')));
 page.on('request',r=>{if(r.url().startsWith(app.origin+'/'))report.requests.push({path:new URL(r.url()).pathname,method:r.method()});else if(!r.url().startsWith('blob:'))report.errors.push('Unexpected external request');});
 page.on('response',r=>{if(r.status()>=400)report.errors.push(r.status()+' '+new URL(r.url()).pathname);});
 page.on('dialog',d=>d.dismiss());
 const idle=()=>page.waitForFunction(()=>!document.body.classList.contains('working'));
 const click=async action=>{await page.locator('[data-action="'+action+'"]').click();await idle();};
 const ready=async()=>{await idle();await page.waitForFunction(()=>['ready','failed'].includes(document.querySelector('[data-scene-viewer]')?.dataset.viewerState),null,{timeout:205000});assert.equal(await page.locator('[data-scene-viewer]').getAttribute('data-viewer-state'),'ready',await page.locator('[data-scene-viewer]').innerText());};
 const candidate=async()=>{await page.waitForFunction(()=>{const save=document.querySelector('[data-action="save-world"]');return save&&!save.disabled;},null,{timeout:205000});await ready();return state();};
 await page.goto(app.origin+'/workbench#'+app.token);await idle();await page.locator('[data-action="project"][data-id="'+p.id+'"]').click();await ready();
 assert.deepEqual(await fileHash(path.join(p.directory,'project.json')),manifestBefore);
 assert.equal(report.requests.some(r=>r.method==='POST'&&/world-prepare/.test(r.path)),false);
 report.checks.push('Opening older saved imports displays unchanged geometry and explicit placement check, without preparation or project rewrite');
 await click('world-prepare-inspect');await page.getByRole('heading',{name:'Enable asset placement',exact:true}).waitFor({timeout:205000});await idle();
 const choices=page.locator('[name="world-prepare-group"]:enabled');assert.equal(await choices.count(),3);assert.equal(await page.locator('[name="world-prepare-group"]:checked').count(),0);assert.equal(await page.locator('[data-action="world-prepare-confirm"]').isDisabled(),true);
 let v=await state(),s=v.project.workbench.scenes[0];assert.equal(s.current,cpId);assert.equal(s.candidate,null);assert.deepEqual(s.completed,{world:cpId});
 const inspected=v.runs.find(r=>r.action==='world-prepare-audit');assert.equal(inspected.state,'SUCCEEDED');assert.equal(inspected.inspection.groups.length,3);
 await page.screenshot({path:path.join(out,'01-explicit-review.png'),fullPage:true});
 await click('close');assert.equal(report.requests.some(r=>r.path.endsWith('/world-prepare')),false);
 await click('world-prepare-inspect');assert.equal(report.requests.filter(r=>r.path.endsWith('/world-prepare-inspect')).length,1);
 report.checks.push('Native read-only check returns exact observed groups; Cancel runs no preparation and reopening reuses the current inspection');
 for(let i=0;i<3;i++)await choices.nth(i).check();await click('world-prepare-confirm');v=await candidate();s=v.project.workbench.scenes[0];
 assert.equal(s.current,cpId);assert(s.candidate);assert.deepEqual(s.completed,{world:cpId});
 const first=s.checkpoints.find(c=>c.id===s.candidate),run=v.runs.find(r=>r.resultCheckpointId===first.id);assert.equal(run.publication,'SEPARATE_CANDIDATE_ONLY');assert.equal(run.state,'SUCCEEDED');report.saved.push(first);
 const native=await app.workbench.result(await app.runtime.job(run.jobId));assert.equal(native.reopened,true);assert.equal(native.groups.length,3);assert.equal(native.visual_acceptance,'NOT_EVALUATED');
 assert.equal(await page.locator('[data-world-pick] option').count(),4);assert.match(await page.locator('.world-savebar').innerText(),/Unsaved changes/);
 assert.deepEqual(await fileHash(path.join(p.directory,relative)),before);await page.screenshot({path:path.join(out,'02-review-candidate.png'),fullPage:true});
 report.checks.push('Explicit selection prepares and reopens a separate native candidate; three real placement bindings appear while current scene and completion remain unchanged');
 await click('world-undo');await ready();v=await state();s=v.project.workbench.scenes[0];assert.equal(s.current,cpId);assert.equal(s.candidate,null);assert.deepEqual(s.completed,{world:cpId});
 assert.deepEqual(await fileHash(path.join(p.directory,first.path)),{sha256:first.sha256,size:first.size});
 await click('world-prepare-inspect');for(let i=0;i<3;i++)await choices.nth(i).check();await click('world-prepare-confirm');v=await candidate();s=v.project.workbench.scenes[0];const second=s.checkpoints.find(c=>c.id===s.candidate);assert.notEqual(second.id,first.id);report.saved.push(second);
 await click('save-world');await ready();v=await state();s=v.project.workbench.scenes[0];assert.equal(s.current,second.id);assert.equal(s.candidate,null);assert.deepEqual(s.completed,{});
 report.checks.push('Undo restores the exact original without deleting candidate evidence; a fresh preparation can be explicitly saved without granting World approval');
 const picker=page.locator('[data-world-pick]'),instance=(await picker.locator('option').evaluateAll(options=>options.map(o=>({id:o.value,name:o.textContent})))).find(o=>o.name==='World placement - SyntheticRig0');assert(instance);
 await picker.selectOption(instance.id);await page.locator('.world-transform-details summary').click();const x=page.getByLabel('Placement X',{exact:true});await x.fill(String(Number(await x.inputValue())+2));await page.locator('[data-world-apply]').click();
 assert.match(await page.locator('.world-savebar').innerText(),/Unsaved placement/);await click('save-world');await ready();v=await state();s=v.project.workbench.scenes[0];assert.notEqual(s.current,second.id);assert.deepEqual(s.completed,{});report.saved.push(s.checkpoints.find(c=>c.id===s.current));
 assert.equal(v.runs.find(r=>r.resultCheckpointId===s.current).action,'world-transform');
 report.checks.push('Prepared character can be moved through the normal in-app controls and explicitly saved by the real transform worker');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'03-saved-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 for(const cp of report.saved)assert.deepEqual(await fileHash(path.join(p.directory,cp.path)),{sha256:cp.sha256,size:cp.size});assert.deepEqual(await fileHash(source),before);assert.deepEqual(await fileHash(path.join(p.directory,relative)),before);assert.deepEqual(report.errors,[]);
 report.checks.push('Original and all candidates remain byte-identical; desktop/mobile flow has no browser or HTTP errors');report.status='PASS';
}catch(error){report.status='FAIL';report.error=String(error.stack||error).replaceAll(app?.token||'never-match-token','[REDACTED]');process.exitCode=1;await page?.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});}
finally{await browser?.close();if(app){app.server.closeAllConnections();await new Promise(resolve=>app.server.close(resolve));}await writeJson(path.join(out,'RESULTS.json'),report);console.log(JSON.stringify({status:report.status,checks:report.checks.length,error:report.error}));}
