import test from 'node:test';
import assert from 'node:assert/strict';
import {timelineDraft} from '../public/action-timeline-draft.mjs';
const take='take_'+'b'.repeat(64),cp={id:'cp_test',sha256:'c'.repeat(64)};
function seed(){const audit={id:'run_test',inspection:{sha256:'d'.repeat(64),fps:24,frame_range:[1,120],performers:[{name:'Rig',takes:[{id:take,range:[1,25],heading_blocker:null,travel_blocker:null,stitch_blocker:null,stitch_channels:'e'.repeat(64),gait:{status:'estimated',id:'f'.repeat(64),meters_per_cycle:1,direction:[1,0]}}],timeline:{version:'action-timeline-v1',stitch_version:'native-stitch-v1',edit_version:'native-motion-edit-v1',clips:[],origin_m:[0,0,0],meters_per_unit:1}}]}};return {audit,d:timelineDraft(cp,audit)};}
test('visual turn is one undoable gesture including automatic connection mode',()=>{const {d}=seed();d.add(take,'clip_a');d.add(take,'clip_b');d.select('Rig','clip_b','transition');const before=d.clips('Rig');d.rotateHeading(5);d.rotateHeading(20);d.rotateHeading(45);assert.equal(d.selectedClip.heading_deg,45);assert.equal(d.selectedClip.transition.mode,'turn');assert.equal(d.selectedClip.transition.match_phase,false);assert(!d.invalid);d.finishEdit();d.undo();assert.deepEqual(d.clips('Rig'),before);});
test('visual heading rotates automatic path, preserves manual path and timing',()=>{const {d}=seed();d.add(take,'clip_a');d.edit('travel',true);const frames=d.selectedClip.frames;d.rotateHeading(90);assert(Math.abs(d.selectedClip.travel.delta_m[0])<1e-8);assert.equal(d.selectedClip.travel.delta_m[1],1);assert.equal(d.selectedClip.frames,frames);assert(!d.invalid);d.edit('automatic',false);const path=d.selectedClip.travel.delta_m;d.rotateHeading(30);assert.deepEqual(d.selectedClip.travel.delta_m,path);});
test('unconnected later animation and unsupported native heading refuse without changing draft',()=>{const {d,audit}=seed();d.add(take,'clip_a');d.add(take,'clip_b');d.edit('smooth',false);const before=d.clips('Rig');assert.throws(()=>d.rotateHeading(15),/Connect/);assert.deepEqual(d.clips('Rig'),before);d.select('Rig','clip_a');audit.inspection.performers[0].takes[0].heading_blocker='Unsupported root';assert.throws(()=>d.rotateHeading(15),/Unsupported root/);assert.deepEqual(d.clips('Rig'),before);});
test('ring wraps angles but does not waive native 135 degree turn limit or reviews',()=>{const {d}=seed();d.add(take,'clip_a');d.add(take,'clip_b');d.rotateHeading(181);assert.equal(d.selectedClip.heading_deg,-179);assert(d.invalid);assert.throws(()=>d.request('run_save'),/135/);assert.equal(d.selectedClip.repeat_reviewed,false);d.rotateHeading(45);assert(!d.invalid);});
test('zero rotation does not convert or dirty a saved connection',()=>{const {d,audit}=seed();d.add(take,'clip_a');d.add(take,'clip_b');audit.inspection.performers[0].timeline.clips=d.clips('Rig');const clean=timelineDraft(cp,audit);clean.select('Rig','clip_b','transition');clean.rotateHeading(360);assert(!clean.dirty);assert(!clean.canUndo);assert.equal(clean.selectedClip.transition.mode,undefined);});
